project:
  type: book
  output-dir: docs

book:
  title: "Learning-Diary"
  author: "Luo Huangchen"
  date: "2025/3/27"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - Week9.qmd
    - references.qmd

bibliography: references.bib
csl: harvard-cite-them-right.csl

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

